# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 681, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.menu = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.menu.setContentsMargins(11, 11, 11, 11)
        self.menu.setSpacing(6)
        self.menu.setObjectName("menu")
        self.Button_AddClassify = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_AddClassify.setObjectName("Button_AddClassify")
        self.menu.addWidget(self.Button_AddClassify)
        self.Button_AddIncome = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_AddIncome.setObjectName("Button_AddIncome")
        self.menu.addWidget(self.Button_AddIncome)
        self.Button_AddSpending = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Button_AddSpending.setObjectName("Button_AddSpending")
        self.menu.addWidget(self.Button_AddSpending)
        self.Button_AddIncome.raise_()
        self.Button_AddSpending.raise_()
        self.Button_AddClassify.raise_()
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 701, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 681, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Classify = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_Classify.setObjectName("Button_Classify")
        self.horizontalLayout.addWidget(self.Button_Classify)
        self.Button_Income = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_Income.setObjectName("Button_Income")
        self.horizontalLayout.addWidget(self.Button_Income)
        self.Button_Spending = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_Spending.setObjectName("Button_Spending")
        self.horizontalLayout.addWidget(self.Button_Spending)
        self.Button_Count = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_Count.setObjectName("Button_Count")
        self.horizontalLayout.addWidget(self.Button_Count)
        self.Button_AccountInformation = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.Button_AccountInformation.setObjectName("Button_AccountInformation")
        self.horizontalLayout.addWidget(self.Button_AccountInformation)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menuBar.setObjectName("menuBar")
        self.Menu_File = QtWidgets.QMenu(self.menuBar)
        self.Menu_File.setObjectName("Menu_File")
        self.Menu_Editor = QtWidgets.QMenu(self.menuBar)
        self.Menu_Editor.setObjectName("Menu_Editor")
        self.Menu_View = QtWidgets.QMenu(self.menuBar)
        self.Menu_View.setObjectName("Menu_View")
        self.Menu_About = QtWidgets.QMenu(self.menuBar)
        self.Menu_About.setObjectName("Menu_About")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.Menu_File_NewAccount = QtWidgets.QAction(MainWindow)
        self.Menu_File_NewAccount.setObjectName("Menu_File_NewAccount")
        self.Menu_Editor_AddClassify = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_AddClassify.setObjectName("Menu_Editor_AddClassify")
        self.Menu_View_Language = QtWidgets.QAction(MainWindow)
        self.Menu_View_Language.setObjectName("Menu_View_Language")
        self.Menu_About_Update = QtWidgets.QAction(MainWindow)
        self.Menu_About_Update.setObjectName("Menu_About_Update")
        self.Menu_File_OpenAccount = QtWidgets.QAction(MainWindow)
        self.Menu_File_OpenAccount.setObjectName("Menu_File_OpenAccount")
        self.Menu_File_BackupAccount = QtWidgets.QAction(MainWindow)
        self.Menu_File_BackupAccount.setObjectName("Menu_File_BackupAccount")
        self.Menu_File_ChangeAccountPath = QtWidgets.QAction(MainWindow)
        self.Menu_File_ChangeAccountPath.setObjectName("Menu_File_ChangeAccountPath")
        self.Menu_File_SetSecure = QtWidgets.QAction(MainWindow)
        self.Menu_File_SetSecure.setObjectName("Menu_File_SetSecure")
        self.Menu_File_Input = QtWidgets.QAction(MainWindow)
        self.Menu_File_Input.setObjectName("Menu_File_Input")
        self.Menu_File_Output = QtWidgets.QAction(MainWindow)
        self.Menu_File_Output.setObjectName("Menu_File_Output")
        self.Menu_File_exit = QtWidgets.QAction(MainWindow)
        self.Menu_File_exit.setObjectName("Menu_File_exit")
        self.Menu_Editor_AddIncome = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_AddIncome.setObjectName("Menu_Editor_AddIncome")
        self.Menu_Editor_AddSpending = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_AddSpending.setObjectName("Menu_Editor_AddSpending")
        self.actiond_3 = QtWidgets.QAction(MainWindow)
        self.actiond_3.setObjectName("actiond_3")
        self.Menu_Editor_Classify = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_Classify.setObjectName("Menu_Editor_Classify")
        self.Menu_Editor_Income = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_Income.setObjectName("Menu_Editor_Income")
        self.Menu_Editor_Spending = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_Spending.setObjectName("Menu_Editor_Spending")
        self.Menu_Editor_Count = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_Count.setObjectName("Menu_Editor_Count")
        self.Menu_Editor_AccountInformation = QtWidgets.QAction(MainWindow)
        self.Menu_Editor_AccountInformation.setObjectName("Menu_Editor_AccountInformation")
        self.Menu_About_Author = QtWidgets.QAction(MainWindow)
        self.Menu_About_Author.setObjectName("Menu_About_Author")
        self.Menu_File.addAction(self.Menu_File_NewAccount)
        self.Menu_File.addAction(self.Menu_File_OpenAccount)
        self.Menu_File.addAction(self.Menu_File_BackupAccount)
        self.Menu_File.addAction(self.Menu_File_ChangeAccountPath)
        self.Menu_File.addSeparator()
        self.Menu_File.addAction(self.Menu_File_SetSecure)
        self.Menu_File.addSeparator()
        self.Menu_File.addAction(self.Menu_File_Input)
        self.Menu_File.addAction(self.Menu_File_Output)
        self.Menu_File.addSeparator()
        self.Menu_File.addAction(self.Menu_File_exit)
        self.Menu_Editor.addAction(self.Menu_Editor_AddClassify)
        self.Menu_Editor.addAction(self.Menu_Editor_AddIncome)
        self.Menu_Editor.addAction(self.Menu_Editor_AddSpending)
        self.Menu_Editor.addSeparator()
        self.Menu_Editor.addAction(self.Menu_Editor_Classify)
        self.Menu_Editor.addAction(self.Menu_Editor_Income)
        self.Menu_Editor.addAction(self.Menu_Editor_Spending)
        self.Menu_Editor.addAction(self.Menu_Editor_Count)
        self.Menu_Editor.addAction(self.Menu_Editor_AccountInformation)
        self.Menu_View.addAction(self.Menu_View_Language)
        self.Menu_About.addAction(self.Menu_About_Update)
        self.Menu_About.addAction(self.Menu_About_Author)
        self.menuBar.addAction(self.Menu_File.menuAction())
        self.menuBar.addAction(self.Menu_Editor.menuAction())
        self.menuBar.addAction(self.Menu_View.menuAction())
        self.menuBar.addAction(self.Menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "记账"))
        self.Button_AddClassify.setText(_translate("MainWindow", "添加分类"))
        self.Button_AddIncome.setText(_translate("MainWindow", "添加收入"))
        self.Button_AddSpending.setText(_translate("MainWindow", "添加支出"))
        self.Button_Classify.setText(_translate("MainWindow", "分类"))
        self.Button_Income.setText(_translate("MainWindow", "收入列表"))
        self.Button_Spending.setText(_translate("MainWindow", "支出列表"))
        self.Button_Count.setText(_translate("MainWindow", "统计"))
        self.Button_AccountInformation.setText(_translate("MainWindow", "账户信息"))
        self.Menu_File.setTitle(_translate("MainWindow", "文件"))
        self.Menu_Editor.setTitle(_translate("MainWindow", "编辑"))
        self.Menu_View.setTitle(_translate("MainWindow", "查看"))
        self.Menu_About.setTitle(_translate("MainWindow", "关于"))
        self.Menu_File_NewAccount.setText(_translate("MainWindow", "新建账户"))
        self.Menu_Editor_AddClassify.setText(_translate("MainWindow", "添加分类"))
        self.Menu_View_Language.setText(_translate("MainWindow", "语言"))
        self.Menu_About_Update.setText(_translate("MainWindow", "自动更新"))
        self.Menu_File_OpenAccount.setText(_translate("MainWindow", "打开账户"))
        self.Menu_File_BackupAccount.setText(_translate("MainWindow", "备份账户"))
        self.Menu_File_ChangeAccountPath.setText(_translate("MainWindow", "更改账户路径"))
        self.Menu_File_SetSecure.setText(_translate("MainWindow", "设置密码"))
        self.Menu_File_Input.setText(_translate("MainWindow", "导入"))
        self.Menu_File_Output.setText(_translate("MainWindow", "导出"))
        self.Menu_File_exit.setText(_translate("MainWindow", "退出"))
        self.Menu_Editor_AddIncome.setText(_translate("MainWindow", "添加收入"))
        self.Menu_Editor_AddSpending.setText(_translate("MainWindow", "添加支出"))
        self.actiond_3.setText(_translate("MainWindow", "d"))
        self.Menu_Editor_Classify.setText(_translate("MainWindow", "分类"))
        self.Menu_Editor_Income.setText(_translate("MainWindow", "收入列表"))
        self.Menu_Editor_Spending.setText(_translate("MainWindow", "支出列表"))
        self.Menu_Editor_Count.setText(_translate("MainWindow", "统计"))
        self.Menu_Editor_AccountInformation.setText(_translate("MainWindow", "账户信息"))
        self.Menu_About_Author.setText(_translate("MainWindow", "作者"))

