# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_addincome.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_AddIncome(QtWidgets.QDialog):
    def setupUi(self, Dialog_AddIncome):
        Dialog_AddIncome.setObjectName("Dialog_AddIncome")
        Dialog_AddIncome.resize(411, 382)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 120, 151, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 20, 102, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.verticalLayout_11.addWidget(self.dateEdit_2)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(80, 290, 291, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_9)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_12.addWidget(self.checkBox_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 41, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(20, 170, 41, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(80, 170, 291, 101))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_4)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_15.addWidget(self.plainTextEdit_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 70, 151, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout_16.addWidget(self.comboBox_2)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 70, 41, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_17.addWidget(self.label_7)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 120, 41, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_18.addWidget(self.label_8)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_AddIncome)
        self.buttonBox.setGeometry(QtCore.QRect(230, 340, 164, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(200, 20, 62, 31))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(Dialog_AddIncome)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(280, 20, 102, 31))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget_11)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_19.addWidget(self.timeEdit)

        self.retranslateUi(Dialog_AddIncome)
        QtCore.QMetaObject.connectSlotsByName(Dialog_AddIncome)

    def retranslateUi(self, Dialog_AddIncome):
        _translate = QtCore.QCoreApplication.translate
        Dialog_AddIncome.setWindowTitle(_translate("Dialog_AddIncome", "Dialog"))
        self.checkBox_2.setText(_translate("Dialog_AddIncome", "不关闭对话框，继续添加"))
        self.label_5.setText(_translate("Dialog_AddIncome", "日期："))
        self.label_6.setText(_translate("Dialog_AddIncome", "说明："))
        self.comboBox_2.setItemText(0, _translate("Dialog_AddIncome", "工资"))
        self.label_7.setText(_translate("Dialog_AddIncome", "分类："))
        self.label_8.setText(_translate("Dialog_AddIncome", "金额："))
        self.label.setText(_translate("Dialog_AddIncome", "时间："))

