# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_addspending.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_AddSpending(QtWidgets.QDialog):
    def setupUi(self, Dialog_AddSpending):
        Dialog_AddSpending.setObjectName("Dialog_AddSpending")
        Dialog_AddSpending.resize(411, 441)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 41, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 41, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 20, 101, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_3.addWidget(self.dateEdit)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(80, 70, 191, 31))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(80, 120, 191, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_5.addWidget(self.comboBox_2)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 120, 41, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 170, 41, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(80, 170, 191, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_8.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(20, 220, 41, 31))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(80, 220, 311, 101))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_10)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_10.addWidget(self.plainTextEdit)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(80, 340, 191, 31))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_11)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_11.addWidget(self.checkBox)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(200, 390, 191, 32))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_12)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_12.addWidget(self.buttonBox)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(199, 19, 41, 31))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(Dialog_AddSpending)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(260, 20, 102, 31))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget_14)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_14.addWidget(self.timeEdit)

        self.retranslateUi(Dialog_AddSpending)
        QtCore.QMetaObject.connectSlotsByName(Dialog_AddSpending)

    def retranslateUi(self, Dialog_AddSpending):
        _translate = QtCore.QCoreApplication.translate
        Dialog_AddSpending.setWindowTitle(_translate("Dialog_AddSpending", "Dialog"))
        self.label_5.setText(_translate("Dialog_AddSpending", "日期："))
        self.label.setText(_translate("Dialog_AddSpending", "分类："))
        self.label_2.setText(_translate("Dialog_AddSpending", "支付："))
        self.label_3.setText(_translate("Dialog_AddSpending", "金额："))
        self.label_4.setText(_translate("Dialog_AddSpending", "说明："))
        self.checkBox.setText(_translate("Dialog_AddSpending", "不关闭对话框，继续添加"))
        self.label_6.setText(_translate("Dialog_AddSpending", "时间："))

